# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-24 05:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161224_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='enabled',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='full_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='signin_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sign In'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='signout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sign Out'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 12, 24, 5, 12, 15, 377987, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 12, 24, 5, 12, 21, 221990, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='relationships',
            name='child',
            field=models.ManyToManyField(related_name='is_child', to='events.Person'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='guardian',
            field=models.ManyToManyField(related_name='is_guardian', to='events.Person'),
        ),
    ]
