# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-24 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20161224_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationships',
            old_name='child',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='relationships',
            old_name='guardian',
            new_name='guardians',
        ),
    ]
